<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c5d120d5-d415-431c-80d5-2f5e53938ec2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.MySql" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MinhaApi.IoC\MinhaApi.IoC.csproj" />
    <ProjectReference Include="..\MinhaApi.Application\MinhaApi.Application.csproj" />
    <ProjectReference Include="..\MinhaApi.DataTransfer\MinhaApi.DataTransfer.csproj" />
    <ProjectReference Include="..\MinhaApi.CrossCutting\MinhaApi.CrossCutting.csproj" />
  </ItemGroup>

</Project>
